# Generated by Django 5.0.2 on 2024-02-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_Name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField()),
            ],
        ),
    ]
