# Generated by Django 5.0.2 on 2024-02-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='applied_Role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
